### ISSUE TITLE
SPA refresh to login

### ISSUE THREAD

**Issue by luukhoeben** [websanova/vue-auth#24] opened 2016-09-16 11:54 UTC
Hey,

Got a question, everytime I log in on my SPA (where I use your package) I go to the protected redirect route and then I can do everything I want/need, but then when I refresh it refreshes the token and sends me back to the login screen..

Can you help me with that? (if I need to give aditional information or something just tell me what you need)

Thanks in advance :)
- Luuk

**Comment by websanova** [comment] 2016-09-16 11:58
What version are you using?

**Comment by luukhoeben** [comment] 2016-09-16 11:59
oh sorry.. forgot to tell you that. I'm using `^1.0.9-dev`. I installed using npm install @websanova/vue-auth so I guess I just got the newest version, right?

**Comment by websanova** [comment] 2016-09-16 12:04
Ok, when you refresh, do you see any requests being made, to fetch a user or anything like that?

I'm suspecting there is an issue with the tokens from the server being invalid, which would then kick you back to the login

**Comment by luukhoeben** [comment] 2016-09-16 12:11
Ehm yeah I see the refresh request but no additional user request.. I use the laravel tymonsdesigns/jwt-auth plugin..

Also when I login (without the refresh, so I can get to everything still) the `$auth.user()` is undefined.

I just return a json response with the user for the user route, as for the refresh route, It is in the headers but I also return it as json `{ token: 'very_long_token_string' }`

**Comment by websanova** [comment] 2016-09-16 12:18
Hmm, so when do the login, you get a token right. So can you try taking that token (from the response) and do the call manually through a REST client directly to the api.

Also note that I have a demo server up that uses Laravel and the same plugin here that might help if the issue is on the api end. 

https://github.com/websanova/laravel-api-demo

**Comment by luukhoeben** [comment] 2016-09-16 12:27
I think theres something wrong on the api side.. Tho I was looking at the refresh function in your api..

It doesn't refresh the token, or does it?

```
public function refresh()
{
    return response([
         'status' => 'success'
    ]);
}
```

**Comment by luukhoeben** [comment] 2016-09-16 12:46
I gave a different response back, that's fixed now.. I can fetch the user correctly now, only thing is the refresh still kicks me back to the login page.. just implemented it the same way as you did in the example.

( It refreshes it in the localstorage still, and I get a different one back then I sent but somehow still invalid or something)

**Comment by websanova** [comment] 2016-09-16 13:00
Ya, so the vue-auth module has some hooks to auto detect anytime a proper header a return parameter is set, so you can actually inject a token at any time during one of the auth calls and it would pick it up.

However in your case it seems the tokens are getting invalidated. You should really be testing outside the plugin manually. For instance it just happens to be the `refresh` that kicks you because that is the first thing that is getting called, but I would assume any call to the server with that token would return an invalid response.

On a side note, you may also want to check the JWT settings, I remember having some weird issues on that end as well. I think I had to set `blacklist_enabled` to false.

In `config/jwt.php`:

    'secret' => env('JWT_SECRET', 'somekeyhere'),
    'blacklist_enabled' => env('JWT_BLACKLIST_ENABLED', true),

In `.env`:

    JWT_SECRET=somekeyhere=
    JWT_BLACKLIST_ENABLED=false

**Comment by luukhoeben** [comment] 2016-09-16 13:03
I'll try that and I'll try to test it outside of the plugin. Thanks for the help and patience so far :smile:

I'll let you know what it was when I find it!

**Comment by luukhoeben** [comment] 2016-09-16 17:26
I don't get it, I just installed your example server, changed all the endpoints to match and it still did exactly the same thing..

Do you have any idea what I can do to debug or fix this?

**Comment by websanova** [comment] 2016-09-16 18:06
Well what does the response say when the refresh occurs?

**Comment by luukhoeben** [comment] 2016-09-16 18:30
I've got this:
```
Route::get('/auth/refresh', function (Request $request) {
	return response([
		'status' => 'success'
	]);
})->middleware('jwt.refresh');
```
in my routes file just like in your example.. In the middleware everything is okay so it returns `{ status: "success" }` with the Authorization header. for example: 
```Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjQsImlzcyI6Imh0dHA6XC9cL3JtaS5kZXZcL2FwaVwvYXV0aFwvcmVmcmVzaCIsImlhdCI6MTQ3NDA1MDU3MSwiZXhwIjoxNDc0MDU0MTcyLCJuYmYiOjE0NzQwNTA1NzIsImp0aSI6ImI3YjVjYjJiMTEzYWQxYWMyZWZhNGZjOTBhMzE5NWU3In0.OXgU7XolW9GspKVnTSxHPHfNUcBAeT2FSVPJgNO-3Qk```

**Comment by websanova** [comment] 2016-09-17 01:13
Ok, sonic you take that token and make a request it works?

**Comment by luukhoeben** [comment] 2016-09-17 09:11
You mean if I manually paste it in httpie to the refresh for example, if I get a success status and a new one back?

That I do. I just get a new one and the success message described in the route.

**Comment by websanova** [comment] 2016-09-17 11:44
Ok, so can you try taking that same token and make a few different requests
manually, like an auth, or whatever, see if they all work with that same
token.

**Comment by luukhoeben** [comment] 2016-09-17 11:48
Yes I can, If I take the refresh token and I make a get request to the /user page (so I should get the user information) I get a `200:OK` and just the success status and the user. then if I remove 1 letter it says: `{ "error": "token_invalid" }` as it should.

**Comment by websanova** [comment] 2016-09-17 15:15
Hmm, do you think you could zip up your code and send it to me...

**Comment by luukhoeben** [comment] 2016-09-17 16:21
Sure, to your email or what method of sending do you prefer?

**Comment by websanova** [comment] 2016-09-18 09:04
rob@websanova.com

**Comment by luukhoeben** [comment] 2016-09-18 09:22
Okay, I've sent it to rob@websanova.com :)

**Comment by websanova** [comment] 2016-09-19 18:00
Well it could, not sure how tour routes are setup.

**Comment by luukhoeben** [comment] 2016-09-19 18:09
What does the context property do in your example tho? just for the console log?

**Comment by websanova** [comment] 2016-09-19 19:10
It's just demo, to make sure funds are getting proper context from calling
components

**Comment by luukhoeben** [comment] 2016-09-19 19:18
hmm, when I try your demo app and set it to my test api, it says:
```XMLHttpRequest cannot load http://rmi.dev/api/auth/login. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8000' is therefore not allowed access.```

with my electron app it works to login but not to refresh, is it possible this only works the way I want over https?

**Comment by websanova** [comment] 2016-09-20 03:31
Yes, could be, usually https is required for this party api. But depends
how it's all set up.

**Comment by luukhoeben** [comment] 2016-09-20 06:30
So how can I set if up to work using http for now? Because I'm working locally to test the api aswell.

**Comment by websanova** [comment] 2016-09-20 13:43
I would think that has nothing to do with plugin.

**Comment by luukhoeben** [comment] 2016-09-20 16:00
true, I'll try to push it up to my server for testing and hopefully it works with https. If it doesn't I'll let you know.

**Comment by websanova** [comment] 2016-09-21 16:34
Really not sure without seeing some code.

**Comment by luukhoeben** [comment] 2016-09-21 17:43
Haven't you got the code I sent you? I've sent it to the e-mail address you gave me, maybe in your spamfolder?

**Comment by websanova** [comment] 2016-09-30 00:14
Nope, didn't get anything.

**Comment by luukhoeben** [comment] 2016-09-30 08:25
I'll send it again :)

**Comment by websanova** [comment] 2016-09-30 11:00
Ok, got it now, will take a look.

**Comment by luukhoeben** [comment] 2016-10-02 13:55
Thanks! Have you found anything wrong?

**Comment by websanova** [comment] 2016-10-03 03:25
lol, did you zip up the entire node_modules folder? There is like thousand files in there...

Anyway, this thread is quite old and there have been updates made. I suggest you make sure all your vue packages are all fully updated first.

If you still want to send a sample of your code just put something up on GH for me instead please.

**Comment by luukhoeben** [comment] 2016-10-03 09:24
haha no I didn't include the node_modules.. but there are 2 projects in that folder (the API and the frontend electron app). I'll try to update when I get home and I'll update you on what it does then :).

**Comment by websanova** [comment] 2016-10-19 04:30
Any luck, btw the package is at `v1.3.0-beta` now, so you can also try updating to that which may fix some of your issues.

**Comment by luukhoeben** [comment] 2016-10-19 16:11
Oh hey I'm sorry, I've kind of forgotten about this project for a bit because I got frustrated that I couldn't get it to work, but I'll pick it back up then :) I've updated the package to `v1.3.0-beta` but that doesn't change anything, I will upload the project to github today so you will be able to take a look at it if you want 😄

**Comment by luukhoeben** [comment] 2016-10-19 17:36
I've added you as a collaborator. that makes it so you can see it, right?

**Comment by luukhoeben** [comment] 2016-10-23 15:09
Hey,

Have you had a chance to look at it yet? I'm curious to what I do wrong.

Thanks! 😄

**Comment by neronmoon** [comment] 2016-11-22 15:46
bump!

Just wondered why vue-auth does not use fresh token, that received from /refresh endpoint in /user request. It uses old (blacklisted) token instead. Probably, bug here.

**Comment by nonadmin** [comment] 2016-11-22 15:50
More than likely your /user request went out before the /refresh request and/or response was received.  I thought it was a bug too but then realized it really ought to be on the API to allow old tokens some grace period incase a refresh is pending when other requests come in.

**Comment by neronmoon** [comment] 2016-11-22 16:27
yeah, but, if my tab is a bit stale, and then i click cmd+R -- i got 401 on /user request, because of the stale token. Click cmd+R again -- and all is OK!
That's not what i expected.

**Comment by nonadmin** [comment] 2016-11-22 16:34
When vue-auth launches it fires a refresh request, immediately followed by your user request, so that's the issue.  I do agree that it would probably make sense for the app to wait for its refresh request to complete before allowing other requests to fire but I'm not sure of the amount of work required for that.

**Comment by neronmoon** [comment] 2016-11-22 16:43
Solved by this code:

```
routerBeforeEach: function(cb) {
        function ccb() {
            var token = window.localStorage.getItem('default-' + this.options.tokenName);
            if (this.watch.authenticated === null && token) {
                if ( ! document.cookie.match(/rememberMe/)) {
                    this.options.logoutProcess.call(this, null, {});
                    this.watch.loaded = true
                    return cb.call(this);
                }
                this.watch.authenticated = false
                this.options.fetchPerform.call(this, {success: cb, error: cb});
            } else {
                this.watch.loaded = true;
                return cb.call(this);
            }
        }
        if (this.options.tokenExpired.call(this)) {
            this.options.refreshPerform.call(this, {success: ccb});
        } else {
            ccb();
        }
  }
```

Will @websanova approve pr if i'll create one?

**Comment by websanova** [comment] 2016-11-23 08:13
Are you using the $auth.ready() method?

**Comment by websanova** [comment] 2016-11-23 08:46
Also the thing with the refresh/user firing at same time is because stale
tokens should work for some time. The refresh plugin is ready to swap the
token at any time during any request.

You just happen to see it with the fetch user, but even running them in
sync does not remove the stale token problem on the server and it can still
kick your app at any time if a token is swamped right at the moment the app
fires off more then one request.

We could say the app will only refresh the token once at the beginning but
some people will be refreshing the token on each request.

I think one couple options here are to allow it to allow the user call to
be disabled and then run manually with some call on auth ready.

Another option would be to have a flag to run it in sync. But this also
means slowing the app down on boot due to two calls to the server. So I
don't think I would make it default behavior.

On Nov 23, 2016 16:13, "Rob" <rob@websanova.com> wrote:

Are you using the $auth.ready() method?

**Comment by websanova** [comment] 2016-12-11 06:31
Any updates here? If not will close this off.

**Comment by TeroBlaZe** [comment] 2017-01-14 23:19
@websanova Same here for me. I use SPA and when I reload the web page /refresh and /user requests are sent but /user request fails(token_invalid) Because of /user request was sent with the token blacklisted before. Why this isn't happens with demo app?

**Comment by websanova** [comment] 2017-01-15 01:37
Are you using the latest version?

**Comment by TeroBlaZe** [comment] 2017-01-15 01:45
@websanova Thank you for answer. Yes, I used the latest version. I solved my issue by using beta version of `tymon/jwt-auth` plugin which adds blacklist_grace period.

**Comment by websanova** [comment] 2017-01-15 05:59
You can also read my notes in the docs about this.

https://github.com/websanova/vue-auth/blob/master/README.md#token-refresh

**Closed** 2017-02-13 03:53 UTC
