### ISSUE TITLE
Vue 2.0

### ISSUE THREAD

**Issue by lamberski** [websanova/vue-auth#15] opened 2016-09-07 13:35 UTC
Hi Rob,

Does `vue-jwt-auth` work with Vue 2.0? I've been trying to make it work but without any luck.

> Uncaught TypeError: Cannot read property 'router' of undefined

Above error is displayed when I run below code:

``` javascript
import Vue from 'vue/dist/vue'
import VueRouter from 'vue-router'
import VueResource from 'vue-resource'
import VueAuth from 'vue-jwt-auth'

Vue.use(VueRouter)
Vue.use(VueResource)

var router = new VueRouter({
    mode: 'history',
    routes: [
        {
            path: '/',
            name: 'home',
            auth: true,
            component: require('./pages/Home.vue')
        },
        {
            path: '/login',
            name: 'login',
            component: require('./pages/Login.vue')
        }
    ]
})

Vue.use(VueAuth, {}, router)

const app = new Vue({
    router,
    template: `<router-view></router-view>`
}).$mount('#app')
```

**Comment by websanova** [comment] 2016-09-07 15:35
Haven't tested it yet so no idea. But I'm currently in the middle of an
overhaul which will support all versions much easier.

Hopefully early next week it will be out.

Rob

**Comment by lamberski** [comment] 2016-09-07 20:53
That's great! Looking forward to the new version.

**Comment by jeffcj** [comment] 2016-09-14 02:52
Any update on the new version? Looking forward to using this on a new project with Vue2.

**Comment by websanova** [comment] 2016-09-14 10:35
Hey, it's planned for today :p

**Comment by jeffcj** [comment] 2016-09-14 13:05
Great! Thanks!  Appreciate your hard work on this. It will definitely save me some time.

**Comment by websanova** [comment] 2016-09-14 16:57
Hey, do you have a working sample with Vue 2? I can't even get a simple hello world going.

I put in the latest `vue-loader`, `vue-router`, `vue-resource` and `vue` and it's just full of errors and blank screens.

Doesn't seem like 2.0 is ready for anything yet.

**Comment by jeffcj** [comment] 2016-09-14 17:00
Yes, I do have some working boilerplate. Give me some time to get back to my desk and I'll publish for you.

**Comment by websanova** [comment] 2016-09-14 19:15
Ok, well seems to be an issue with the vue-router for now. I've opened an issue for it:

https://github.com/vuejs/vue-router/issues/659

However, you should also update to the latest version I pushed to day `@websanova/vue-auth` `v1.0.5-dev`.

To pass the router in now it's just an option.

    Vue.use(require('@websanova/vue-auth'), {
        router: router
    });

You'll end up seeing that same error in the issue with the `push` function error.

**Comment by jeffcj** [comment] 2016-09-14 20:11
@websanova Is this helpful? 

"The router instance will be available in all descendants of the root instance as this.$router."

Not sitting at my computer so I can't review code at the moment. Not sure if that applies where you're calling router.beforeEach.

**Comment by jeffcj** [comment] 2016-09-14 20:37
At a basic level beforeEach is working. 

`const router = new VueRouter({
  mode: 'history',
  base: __dirname,
  routes: [
    { path: '/', component: Home },
  ]
})

router.beforeEach(function() {console.log('I am before each');})`

Works as intended.

**Comment by websanova** [comment] 2016-09-14 20:57
Ya, but something strange going on here...

**Comment by jeffcj** [comment] 2016-09-14 21:20
I have noticed that the router passed in through the option is not the same router object you get when you look at the router object within your plugin code (just doing some console logging). I'm not sure why...

**Comment by websanova** [comment] 2016-09-14 22:03
Ok, almost there, try the latest `v1.0.8-dev`. Everything seems to be working for the most part.

However, I see that the `router.go` is doing a page refresh. Did they change something in 2.0?

**Comment by jeffcj** [comment] 2016-09-14 23:02
Apparently so.  .go now seems to be a history position.

```
//2.x
   

	  go (n: number) {
	    this.history.go(n)
	  }
	
```
..and

```
//1.x
go (path) {
	    let replace = false
	    let append = false
	    if (Vue.util.isObject(path)) {
	      replace = path.replace
	      append = path.append
	    }
	    path = this.stringifyPath(path)
	    if (path) {
	      this.history.go(path, replace, append)
	    }
	  }

```

**Comment by websanova** [comment] 2016-09-15 00:34
Seems it's router.push now.

**Comment by websanova** [comment] 2016-09-15 12:51
Ok, I added a tweak to use `push` if it's available and default to `go` otherwise. Seems to be good now, make sure you grab the latest.

Let me know if any other issues come up.

**Comment by kubacode** [comment] 2016-10-12 07:18
Just started upgrading my app to Vue 2 and the ```auth``` property in the routes doesn't seem to be taking affect anymore - I'm able to view routes that should require authentication without being authenticated.

According to the vue-router docs, any 'custom' props should now be contained within a ```meta``` prop - I've tried both leaving the ```auth``` prop at the 'root' of the route, as well as moving it to within the ```meta``` prop with no joy - any pointers to get this working again?

**Comment by websanova** [comment] 2016-10-12 11:37
Hmm, will have to test it..

**Comment by wennercn** [comment] 2016-10-14 09:14
i think add method getRouteAuth in auth.js options  for custom extend it
getRouteAuth(transition){
   //v1
    return (transition.to || transition).auth;
  //v2
    return transtion.meta.auth;
}

**Comment by websanova** [comment] 2016-10-14 10:38
This project had been moved to

https://github.com/websanova/vue-auth

Make sure you get the latest there.

**Comment by wennercn** [comment] 2016-10-18 05:33
yeah , i get it 

like @kubacode  say ,  custom props must in meta

[Router Meta Fields](http://router.vuejs.org/en/advanced/meta.html)

so ,  i think edit the code 
[https://github.com/websanova/vue-auth/blob/master/src/drivers/vue.1.0.0.js#L78](https://github.com/websanova/vue-auth/blob/master/src/drivers/vue.1.0.0.js#L78)

**Comment by websanova** [comment] 2016-10-18 06:24
Yes, I seen that as well, that all the "custom" stuff is in meta now, I will update for it to check in here shortly .

**Comment by wennercn** [comment] 2016-10-18 06:49
so i want add a method in auth.js for custom extend it 
getRouteAuth(){}

and edit L78 in driver..js
`transitionEach.call(_this,(transition.to|| transition).auth, function () { (next || transition.next)(); });`
to
`transitionEach.call(_this, this.options.getRouteAuth(transition), function () { (next || transition.next)(); });`

**Comment by websanova** [comment] 2016-10-18 06:53
This code is already in the driver file, so I don't think it needs to be
broken down further. Probably I will just add a vue 2.0.0 driver so that
there can be separate code streams.

If you need it working now, just override the `_beforeEach` method
altogether.

    _beforeEach: function (routerBeforeEach, transitionEach) {
        var _this = this;

        this.options.router.beforeEach(function (transition, location,
next) {
            routerBeforeEach.call(_this, function () {
                transitionEach.call(_this, (transition.to ||
transition).auth, function () { (next || transition.next)(); });
            });
        })
    },

**Comment by websanova** [comment] 2016-10-18 08:08
I've just pushed an update here `v1.1.1-beta`.

So now it will check for `meta.auth` first: `(transition.meta || {}).auth || (transition.to || transition).auth`.

**Comment by wennercn** [comment] 2016-10-18 08:11
yeah,i konw override the method
thank you 
----
I also met another proble

I set a router auth = true , and direct input URL enter the router ... i get error
`Uncaught TypeError: Cannot read property 'replace' of undefined`

and i found has a issue in vue-router  https://github.com/vuejs/vue-router/issues/795

Have you ever had this problem, and have a solution?

**Comment by wennercn** [comment] 2016-10-18 08:12
that's great new version!

**Comment by HashemQolami** [comment] 2016-10-18 08:25
I forked the repo and I am working on it to add router v2.x support. Will keep you in the loop!

**Comment by wennercn** [comment] 2016-10-18 08:32
Hi @HashemQolami , Did you found a way to solve the history problem?

**Comment by websanova** [comment] 2016-10-18 09:24
Nope, didn't look into that yet.

**Comment by HashemQolami** [comment] 2016-10-18 09:40
@websanova @wennercn Just sent a [PR](https://github.com/websanova/vue-auth/pull/36). Tested in my own project with Vue@2 and VueRouter@2 and everything seems to be working fine, no bugs yet.

**Comment by websanova** [comment] 2016-10-18 10:09
I will have to setup a separate vue2 demo in the code base (so both 1 and 2
can be tested simultaneously). I seen your PR, but can't it just do
`transition.meta.auth` directly on a transition?

**Comment by HashemQolami** [comment] 2016-10-18 11:05
@websanova 

>  I seen your PR, but can't it just do
> `transition.meta.auth` directly on a transition?

Say we have `/foo/bar` route in the routr config, which does NOT have any `meta`  properties, while there is a `auth: true` set on the parent route, the `/foo`.

In that scenario we want the `auth` rule to be applied to the `/foo/bar` as well and not to repeat ourselves. But the `transition.to.meta` would be empty as there is no meta property set on the `bar`. So we have to iterate over the matched routes which includes the `/foo` as well to find the last route in the list having a `meta.auth` in place.

**Comment by websanova** [comment] 2016-10-18 12:11
Are you talking about dealing with sub routes here?

**Comment by HashemQolami** [comment] 2016-10-18 12:18
@websanova Yes, consider the following:

```js
// apps
  {
    path: '/foo',
    name: 'foo',
    component: MasterView,
    meta: {
      auth: true
    },
    children: [
      {
        path: '',
        component: Foo
      },
      {
        path: 'bar',
        name: 'bar',
        component: Bar
      },
      {
        path: ':others',
        component: Others
      }
    ]
  },
```

In that case we don't have to repeat the `auth` meta property for every single nested route.

**Comment by websanova** [comment] 2016-10-18 13:58
yes, makes sense, let me test this.

**Comment by websanova** [comment] 2016-10-18 14:27
I guess children can have children though, so this may need to be a recursive check up to the parent.

**Comment by HashemQolami** [comment] 2016-10-18 14:56
@websanova It does not need a recursive check as the `transition.matched` Array is flatten with nested routes.

For instance for the `/foo/bar/baz` route, the `matched` array would have 3 items, each represents one level of matched routes: `/foo`, `/foo/bar`, `/foo/bar/baz`.

I suggest continuing the discussion in the [PR page](https://github.com/websanova/vue-auth/pull/36). Should I update the PR with the new commits you have done?

**Comment by edimoldovan** [comment] 2016-10-18 16:08
I’ll be starting a admin kind of admin today, based on 2.0, so I’ll most likely refer to this thread later. I can also test/contribute somehow, just let me know where I can help.

**Comment by websanova** [comment] 2016-10-19 04:28
The PR has been merged, it's looking pretty solid now, thx :-)

**Comment by websanova** [comment] 2016-10-19 04:28
Make sure to grab `v1.3.0-beta` for latest.

**Comment by websanova** [comment] 2016-11-29 04:58
Gonna close this off, as it seems version 2 support is quite stable now. Any separate concerns can go in new issues now.

Thx to everyone for help here :-)

**Closed by websanova** 2016-11-29 04:58 UTC
